repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^.+\.html$
      - id: check-json
        exclude: ^\.vscode\/
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-ast
      - id: debug-statements
      - id: check-merge-conflict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [--config=pyproject.toml]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.365
    hooks:
      - id: pyright
