services:
  web:
    ports:
      - "5678:5678"
      - "8000:8000"
    command: [
      "python",
      "-Xfrozen_modules=off",
      "-m",
      "debugpy",
      "--listen",
      "0.0.0.0:5678",
      "-m",
      "makina.manage",
      "runserver",
      "--nothreading",
      "--noreload",
      "0.0.0.0:8000"
    ]
