services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev-runtime
    image: sda/makina:dev
    platform: linux/amd64
    container_name: makina-app
    ports:
      - "8000:8000"
    environment:
      - RUNNING_IN_DOCKER=true
      - DJANGO_SETTINGS_MODULE=makina.core.settings.dev
      - DEBUG=true
      - SECRET_KEY=SuperDuperSecretK3Y
      - DATABASE_URL=postgres://pilot:onawheel@db:5432/makina?encoding=utf-8
      - STRIPE_PUBLISHABLE_KEY=pk_test_51Jw774LmYIXXKBgS40qd7YI2c3no8bGZyGTjkO13uQxLT30DluL0FtAiP9NFEdTgmvAsMqo4d5mOYHQQ9ECTbf0M00Hqmw8Tqw
      - STRIPE_SECRET_KEY=sk_test_51Jw774LmYIXXKBgSRbo66iQcdtPIsiLRixyxySWoYfdsdOE8LAh9MffV60Tjzf7G40FPF1HiKXnuWGxkAIwZU9Rn00GqYCwreg
    volumes:
      - /app/.venv
      - .:/app

  db:
    image: postgres:16-alpine
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_DB=makinat
      - POSTGRES_USER=dontdrink
      - POSTGRES_PASSWORD=anddrive
    container_name: makina-db
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
