version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sda/makina
    container_name: makina-app
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=makinat
      - POSTGRES_USER=driver
      - POSTGRES_PASSWORD=secret
    container_name: makina-db
    ports:
      - "15432:5432"
    volumes:
      - makina-db-data:/var/lib/postgresql/data


volumes:
  makina-db-data:
