databases:
  - name: makinat
    databaseName: makinat
    user: driver
    plan: free

services:
  - type: web
    name: makinat
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: makinat
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_test_51Jw774LmYIXXKBgS40qd7YI2c3no8bGZyGTjkO13uQxLT30DluL0FtAiP9NFEdTgmvAsMqo4d5mOYHQQ9ECTbf0M00Hqmw8Tqw
      - key: STRIPE_SECRET_KEY
        value: sk_test_51Jw774LmYIXXKBgSc9vLE8zLUCBIA9PfynBv9Nq1k5Cugad2CKuXN3Ozcju5exC3GGBDcfiUXjoQ7e1qSFgP02Ae00kaxly7ob
