# Generated by Django 4.1.2 on 2022-10-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("published_on", models.DateTimeField(blank=True, null=True)),
                ("author", models.CharField(max_length=128)),
                ("is_published", models.BooleanField(default=False)),
                ("tags", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "posts",
            },
        ),
    ]
