# Generated by Django 4.1.3 on 2022-11-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in EUR", max_digits=6
                    ),
                ),
                ("photo", models.ImageField(upload_to="products")),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("code",), name="uix_products_code"
            ),
        ),
    ]
