# Generated by Django 4.1.2 on 2022-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
