# Generated by Django 4.1.2 on 2022-10-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_vehicle_user_alter_photo_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price",
            field=models.IntegerField(help_text="Price in Euros"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
