# Generated by Django 5.0.7 on 2024-07-14 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField(help_text="Price in Euros")),
                (
                    "transmission",
                    models.CharField(
                        choices=[("A", "Automatic"), ("M", "Manual")], max_length=1
                    ),
                ),
                (
                    "fuel",
                    models.CharField(
                        choices=[
                            ("diesel", "Diesel"),
                            ("gasoline", "Gasoline"),
                            ("eletric", "Electric"),
                        ],
                        max_length=32,
                    ),
                ),
                ("plates", models.CharField(default="Albanian", max_length=32)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedan", "Sedan"),
                            ("coupet", "Coupet"),
                            ("hatchback", "Hatchback"),
                            ("suv", "SUV"),
                            ("truck", "Truck"),
                        ],
                        max_length=32,
                    ),
                ),
                ("km", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=32)),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="is published?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
                "db_table": "vehicles",
                "permissions": (("publish_vehicle", "Can publish vehicle"),),
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="", verbose_name="picture")),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="vehicles.vehicle",
                        verbose_name="vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo",
                "verbose_name_plural": "photos",
                "db_table": "photos",
            },
        ),
    ]
