# Generated by Django 4.1.2 on 2022-10-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0005_alter_vehicle_description_alter_vehicle_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={
                "permissions": [("publish_vehicle", "Can publish vehicle")],
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
            },
        ),
    ]
